<?xml version="1.0"?>
<rule-set name="safety_isolation_point_decorators"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/java java.xsd">

    <java:import>java.util.HashMap</java:import>

    <java:import>ibanx.services.stproc.StProcHelper</java:import>

    <java:import>ibanx.persistence.object.PersistableIF</java:import>
    <java:import>ibanx.loto.IsolationPointIF</java:import>
    <java:import>java.lang.String</java:import>
    <java:import>ibanx.util.ValueListUtil</java:import>
    <java:import>ibanx.util.ObjectUtil</java:import>
    <java:import>nl.ibanx.turbine.NumberingServiceAdapter</java:import>

    <application-data identifier="log">org.apache.log4j.Logger</application-data>
    <application-data identifier="applicationSettings">ibanx.configuration.ApplicationSettings</application-data>
    <application-data identifier="errors">java.util.Hashtable</application-data>


</rule-set>
