<?xml version="1.0"?>

<rule-set name="tra lifecycle state changes veto rules"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                            http://drools.org/semantics/java java.xsd">

    <java:import>ibanx.event.LifecycleEvent</java:import>
    <java:import>java.util.Hashtable</java:import>
    <java:import>ibanx.util.ObjectUtil</java:import>
    <java:import>ibanx.util.PermitLinkUtil</java:import>
    <java:import>ibanx.util.PermitUtil</java:import>
    <java:import>ibanx.permit.PermitIF</java:import>
    <java:import>ibanx.object.LifecycleManagedIF</java:import>
    <java:import>ibanx.object.BusinessObjectIF</java:import>
    <java:import>ibanx.tra.TaskRiskAnalysisIF</java:import>
    <java:import>ibanx.tra.RiskAssessmentIF</java:import>

    <application-data identifier="log">org.apache.log4j.Logger</application-data>
    <application-data identifier="applicationSettings">ibanx.configuration.ApplicationSettings</application-data>
    <application-data identifier="pluginManager">ibanx.plugin.PluginManager</application-data>

</rule-set>
