data:
  build: data
tomcat7:
  image: codenvy/jdk7_tomcat7
  volumes_from:
   - data
  environment:
   - CATALINA_BASE=/tomcat
   - CATALINA_OPTS=-Dunite.environment=acceptance
   - JAVA_OPTS=-Xmx512m -XX:MaxPermSize=512m -XX:+UseConcMarkSweepGC
  links:
   - data
   - unitedb
   - jackrabbitdb
  ports:
   - "8888:8080"
unitedb:
  image: mysql:5.6
  expose:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=unite
jackrabbitdb:
  image: mysql:5.6
  expose:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=unite_repository

