data:
  build: data
tomcat7:
  image: codenvy/jdk7_tomcat7
  volumes_from:
   - data
  environment:
   - CATALINA_BASE=/tomcat
   - JAVA_OPTS=-Dunite.environment=acceptance
  links:
   - data
   - mysql_unite
   - mysql_jack
  ports:
   - "8888:8080"
mysql_unite:
  image: mysql:5.6
  expose:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=unite
mysql_jack:
  image: mysql:5.6
  expose:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=unite_repository

