<?xml version="1.0"?>

<rule-set name="deltalinqs_permit_state_entry_validators"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                            http://drools.org/semantics/java java.xsd">

    <java:import>ibanx.event.LifecycleEvent</java:import>
    <java:import>java.util.Hashtable</java:import>
    <java:import>ibanx.util.ObjectUtil</java:import>
    <java:import>ibanx.util.PermitLinkUtil</java:import>
    <java:import>ibanx.util.PermitUtil</java:import>
    <java:import>ibanx.permit.PermitIF</java:import>
    <java:import>ibanx.object.LifecycleManagedIF</java:import>
    <java:import>ibanx.object.BusinessObjectIF</java:import>
    <java:import>ibanx.tra.TaskRiskAnalysisIF</java:import>
    <java:import>ibanx.tra.RiskAssessmentIF</java:import>

    <application-data identifier="log">org.apache.log4j.Logger</application-data>
    <application-data identifier="applicationSettings">ibanx.configuration.ApplicationSettings</application-data>
    <application-data identifier="pluginManager">ibanx.plugin.PluginManager</application-data>

    <rule name="RbhRequired" salience="400">
        <parameter identifier="event"><class>LifecycleEvent</class></parameter>
        <parameter identifier="permit"><class>PermitIF</class></parameter>
        <parameter identifier="result"><class>Hashtable</class></parameter>
        <java:condition>!result.containsKey("RbhRequired")</java:condition>
        <java:condition>applicationSettings.isEnabled("ra","permitRbhRequired")</java:condition>
        <java:condition>ObjectUtil.hasValue(event.getCurrentState(), "name", "I_BR")</java:condition>
        <java:condition>ObjectUtil.hasValue(event.getNextState(), "name", "I_MV")</java:condition>
        <java:condition>!event.getNextState().isExceptionState()</java:condition>
		<java:condition>!permit.isNewPermitFormRiskAssessment()</java:condition>
		<java:condition>!PermitLinkUtil.hasRiskAssessment(permit)</java:condition>
        <java:consequence>
            String messageKey = "RbhRequired";
            result.put(messageKey, messageKey);
            drools.modifyObject(result);
        </java:consequence>
    </rule>
    <rule name="RbhIsNotFinished" salience="400">
        <parameter identifier="event"><class>LifecycleEvent</class></parameter>
        <parameter identifier="relatedRbh"><class>RiskAssessmentIF</class></parameter>
        <parameter identifier="result"><class>Hashtable</class></parameter>
        <java:condition>!result.containsKey("RbhIsNotFinished")</java:condition>
        <java:condition>applicationSettings.isEnabled("ra","permitRbhFinishedRequired")</java:condition>
        <java:condition>ObjectUtil.hasValue(event.getCurrentState(), "name", "I_BR")</java:condition>
        <java:condition>ObjectUtil.hasValue(event.getNextState(), "name", "I_MV")</java:condition>
        <java:condition>!event.getNextState().isExceptionState()</java:condition>
        <java:condition>!relatedRbh.getLifecycleStateName().equals("AFGEROND")</java:condition>
        <java:consequence>
            String messageKey = "RbhIsNotFinished";
            result.put(messageKey, messageKey);
            drools.modifyObject(result);
        </java:consequence>
    </rule>
    <!-- either configure this rule, or use the the ValidateRiskDeterminationListener listener, see eventservice.properties -->
    <rule name="PermitRiskUndetermined" salience="300">
        <parameter identifier="event"><class>LifecycleEvent</class></parameter>
        <parameter identifier="permit"><class>PermitIF</class></parameter>
        <parameter identifier="result"><class>Hashtable</class></parameter>
        <java:condition>!result.containsKey("PermitRiskUndetermined")</java:condition>
        <java:condition>ObjectUtil.hasValue(event.getCurrentState(), "name", "I_BR")</java:condition>
        <java:condition>ObjectUtil.hasValue(event.getNextState(), "name", "I_MV")</java:condition>
        <java:condition>!event.getNextState().isExceptionState()</java:condition>
        <java:condition>ObjectUtil.hasValue(permit,"riscCategory","0")</java:condition>
        <java:consequence>
            String messageKey = "PermitRiskUndetermined";
            result.put(messageKey, messageKey);
            drools.modifyObject(result);
        </java:consequence>
    </rule>

    <rule name="HighRiscPermitTraRequired" salience="200">
        <parameter identifier="event"><class>LifecycleEvent</class></parameter>
        <parameter identifier="permit"><class>PermitIF</class></parameter>
        <parameter identifier="result"><class>Hashtable</class></parameter>
        <java:condition>!result.containsKey("HighRiscPermitTraRequired")</java:condition>
		<java:condition>applicationSettings.isEnabled("tra")</java:condition>
        <java:condition>ObjectUtil.hasValue(event.getCurrentState(), "name", "I_BR")</java:condition>
        <java:condition>ObjectUtil.hasValue(event.getNextState(), "name", "I_MV")</java:condition>
        <java:condition>!event.getNextState().isExceptionState()</java:condition>
        <java:condition>ObjectUtil.hasValue(permit,"riscCategory","1")</java:condition>
        <java:condition>ObjectUtil.hasValue(permit,"avTraRequired","Yes")</java:condition>
        <java:condition>!PermitLinkUtil.hasTRA(permit)</java:condition>
        <java:consequence>
            String messageKey = "HighRiscPermitTraRequired";
            result.put(messageKey, messageKey);
            drools.modifyObject(result);
        </java:consequence>
    </rule>

    <!-- either configure this rule, or use the the ValidateJSAListener listener, see eventservice.properties -->
    <rule name="TraIsNotApproved" salience="100">
        <parameter identifier="event"><class>LifecycleEvent</class></parameter>
        <parameter identifier="relatedTra"><class>TaskRiskAnalysisIF</class></parameter>
        <parameter identifier="result"><class>Hashtable</class></parameter>
        <java:condition>!result.containsKey("TraIsNotApproved")</java:condition>
        <java:condition>applicationSettings.isEnabled("tra","permitTraApprovedRequired")</java:condition>
        <java:condition>ObjectUtil.hasValue(event.getCurrentState(), "name", "I_MV")</java:condition>
        <java:condition>ObjectUtil.hasAnyValue(event.getNextState(), "name", "B_MO1,B_MO2,B_MO3,I_VV,I_AMH")</java:condition>
        <java:condition>!event.getNextState().isExceptionState()</java:condition>
        <java:condition>!relatedTra.getLifecycleState().getName().equals("GOEDGEKEURD")</java:condition>
        <java:condition>!relatedTra.getLifecycleState().getName().equals("GEEVALUEERD")</java:condition>
        <java:consequence>
            String messageKey = "TraIsNotApproved";
            result.put(messageKey, messageKey);
            drools.modifyObject(result);
        </java:consequence>
    </rule>
    <!--
    <rule name="alwaysBlockingRule">
        <parameter identifier="result"><class>Hashtable</class></parameter>
        <java:condition>!result.containsKey("alwaysBlockingRule")</java:condition>
        <java:consequence>
            String messageKey = "alwaysBlockingRule";
            result.put(messageKey, messageKey);
        </java:consequence>
    </rule>
    -->

    <rule name="handout-validate-startdate-not-before-6-days-ago" salience="1000">
        <parameter identifier="event"><class>LifecycleEvent</class></parameter>
        <parameter identifier="permit"><class>PermitIF</class></parameter>
        <parameter identifier="result"><class>Hashtable</class></parameter>
        <java:condition>!result.containsKey("PlannedStartDateTooLongInThePast")</java:condition>
        <java:condition>ObjectUtil.hasValue(event.getNextState(), "name", "O_AC")</java:condition>
        <java:condition>ObjectUtil.isBeforeOffsetDateBasedOnToday(permit.getPlannedStartDate(), "-6d")</java:condition>
        <java:consequence>
            String messageKey = "PlannedStartDateTooLongInThePast";
            result.put(messageKey, messageKey);
            drools.modifyObject(result);
        </java:consequence>
    </rule>
    <rule name="handout-validate-startdate-before-enddate" salience="1000">
        <parameter identifier="event"><class>LifecycleEvent</class></parameter>
        <parameter identifier="permit"><class>PermitIF</class></parameter>
        <parameter identifier="result"><class>Hashtable</class></parameter>
        <java:condition>!result.containsKey("PlannedStartDateAfterPlannedEndDate")</java:condition>
        <java:condition>ObjectUtil.hasValue(event.getNextState(), "name", "O_AC")</java:condition>
        <java:condition>ObjectUtil.isBefore(permit.getPlannedEndDate(), permit.getPlannedStartDate())</java:condition>
        <java:consequence>
            String messageKey = "PlannedStartDateAfterPlannedEndDate";
            result.put(messageKey, messageKey);
            drools.modifyObject(result);
        </java:consequence>
    </rule>
    <rule name="handout-validate-startdate-not-in-the-future" salience="1000">
        <parameter identifier="event"><class>LifecycleEvent</class></parameter>
        <parameter identifier="permit"><class>PermitIF</class></parameter>
        <parameter identifier="result"><class>Hashtable</class></parameter>
        <java:condition>!result.containsKey("PlannedStartDateIsInTheFuture")</java:condition>
        <java:condition>ObjectUtil.hasValue(event.getNextState(), "name", "O_AC")</java:condition>
        <java:condition>ObjectUtil.isAfterToday(permit.getPlannedStartDate())</java:condition>
        <java:consequence>
            String messageKey = "PlannedStartDateIsInTheFuture";
            result.put(messageKey, messageKey);
            drools.modifyObject(result);
        </java:consequence>
    </rule>
    <rule name="handout-validate-enddate-not-in-the-past" salience="1000">
        <parameter identifier="event"><class>LifecycleEvent</class></parameter>
        <parameter identifier="permit"><class>PermitIF</class></parameter>
        <parameter identifier="result"><class>Hashtable</class></parameter>
        <java:condition>!result.containsKey("PlannedEndDateIsInThePast")</java:condition>
        <java:condition>ObjectUtil.hasValue(event.getNextState(), "name", "O_AC")</java:condition>
        <java:condition>ObjectUtil.isBeforeToday(permit.getPlannedEndDate())</java:condition>
        <java:consequence>
            String messageKey = "PlannedEndDateIsInThePast";
            result.put(messageKey, messageKey);
            drools.modifyObject(result);
        </java:consequence>
    </rule>
</rule-set>
