<?xml version="1.0"?>

<rule-set name="deltalinqs_permit_message_decorators"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/java java.xsd">

    <java:import>ibanx.object.BusinessObjectIF</java:import>
    <java:import>ibanx.util.ValueListUtil</java:import>
    <java:import>ibanx.util.ObjectUtil</java:import>

    <application-data identifier="log">org.apache.log4j.Logger</application-data>
    <application-data identifier="uiview">ibanx.ui.FailSafeMap</application-data>

    <rule name="validator branden gutsen lassen - BrandwachtInzetten">
        <parameter identifier="object">
            <class>BusinessObjectIF</class>
        </parameter>
        <java:condition>ObjectUtil.hasValue(object,"wwBrandenGutsenLassenRequired","Yes")</java:condition>
        <java:condition>ObjectUtil.hasValue(object,"vzmBrandwachtInzettenRequired","Yes")</java:condition>
        <java:consequence>
            uiview.get("vzmBrandwachtInzettenRequired").setInfoMessage("INFO_wwBrandenGutsenLassenRequired_vzmBrandwachtInzettenRequired");
        </java:consequence>
    </rule>


    <!--<rule name="test rule">
        <parameter identifier="object">
            <class>BusinessObjectIF</class>
        </parameter>
        <java:condition>1==1</java:condition>
        <java:consequence>
            uiview.get("workDescription").setInfoMessage("workDescription");
        </java:consequence>
    </rule>-->

    <!-- BIJZONDERE RICHTLIJNEN -->
    <!--<rule name="validator besloten ruimte - procedure besloten ruimte">
        <parameter identifier="object">
            <class>BusinessObjectIF</class>
        </parameter>
        <java:condition>ObjectUtil.hasValue(object,"wwBetredenBeslotenRuimteRequired","Yes")</java:condition>
        <java:consequence>
            uiview.get("bijzRichtlijnenProcedureBeslotenRuimteRequired").setInfoMessage("INFO_wwBetredenBeslotenRuimteRequired_bijzRichtlijnenProcedureBeslotenRuimteRequired");
        </java:consequence>
    </rule>-->

    <!-- TE NEMEN VOORZORGS MAATREGELEN -->
    <!--<rule name="validator hijsen - valbeveiliging">
        <parameter identifier="object">
            <class>BusinessObjectIF</class>
        </parameter>
        <java:condition>ObjectUtil.hasValue(object,"wwHijsenRequired","Yes")</java:condition>
        <java:consequence>
            uiview.get("vzmWerkplekBeveiligenValgevaarRequired").setInfoMessage("INFO_wwHijsenRequired_vzmWerkplekBeveiligenValgevaarRequired");
        </java:consequence>
    </rule>
    <rule name="validator branden gutsen lassen - vonkafscherming">
        <parameter identifier="object">
            <class>BusinessObjectIF</class>
        </parameter>
        <java:condition>ObjectUtil.hasValue(object,"wwBrandenGutsenLassenRequired","Yes")</java:condition>
        <java:consequence>
            uiview.get("vzmVonkafschermingGebruikenRequired").setInfoMessage("INFO_wwBrandenGutsenLassenRequired_vzmVonkafschermingGebruikenRequired");
        </java:consequence>
    </rule>
    <rule name="validator branden gutsen lassen - poederblussers">
        <parameter identifier="object">
            <class>BusinessObjectIF</class>
        </parameter>
        <java:condition>ObjectUtil.hasValue(object,"wwBrandenGutsenLassenRequired","Yes")</java:condition>
        <java:consequence>
            uiview.get("vzmPoederblusserRequired").setInfoMessage("INFO_wwBrandenGutsenLassenRequired_vzmPoederblusserRequired");
        </java:consequence>
    </rule>
    <rule name="validator branden gutsen lassen - brandwaterslang">
        <parameter identifier="object">
            <class>BusinessObjectIF</class>
        </parameter>
        <java:condition>ObjectUtil.hasValue(object,"wwBrandenGutsenLassenRequired","Yes")</java:condition>
        <java:consequence>
            uiview.get("vzmBrandwaterslangGereedRequired")
                    .setInfoMessage("INFO_wwBrandenGutsenLassenRequired_vzmBrandwaterslangGereedRequired")
                    .setDisabled(true);
        </java:consequence>
    </rule>-->

    <!-- PERSOONLIJKE BESCHERMINGSMIDDELEN -->
    <!--<rule name="validator hijsen - persoonlijke valbescherming">
        <parameter identifier="object">
            <class>BusinessObjectIF</class>
        </parameter>
        <java:condition>ObjectUtil.hasValue(object,"wwHijsenRequired","Yes")</java:condition>
        <java:consequence>
            uiview.get("pbmValbeschermingRequired").setInfoMessage("INFO_wwHijsenRequired_pbmValbeschermingRequired");
        </java:consequence>
    </rule>
    <rule name="validator hakken boren - persoonlijke gehoorbescherming">
        <parameter identifier="object">
            <class>BusinessObjectIF</class>
        </parameter>
        <java:condition>ObjectUtil.hasValue(object,"wwHakkenBorenRequired","Yes")</java:condition>
        <java:consequence>
            uiview.get("pbmGehoorbeschermingRequired").setInfoMessage("INFO_wwHakkenBorenRequired_pbmGehoorbeschermingRequired");
        </java:consequence>
    </rule>
    <rule name="validator product ammoniak - persoonlijke persluchtmasker">
        <parameter identifier="object">
            <class>BusinessObjectIF</class>
        </parameter>
        <java:condition>ObjectUtil.hasValue(object,"product","ammoniak")</java:condition>
        <java:consequence>
            uiview.get("pbmAdembescherming").setInfoMessage("INFO_ammoniak_persluchtmasker");
        </java:consequence>
    </rule>
    <rule name="validator product chloor - persoonlijke persluchtmasker">
        <parameter identifier="object">
            <class>BusinessObjectIF</class>
        </parameter>
        <java:condition>ObjectUtil.hasValue(object,"product","chloor")</java:condition>
        <java:consequence>
            uiview.get("pbmAdembescherming").setInfoMessage("INFO_chloor_persluchtmasker");
        </java:consequence>
    </rule>
    <rule name="validator product isobutaan - persoonlijke persluchtmasker">
        <parameter identifier="object">
            <class>BusinessObjectIF</class>
        </parameter>
        <java:condition>ObjectUtil.hasValue(object,"product","isobutaan")</java:condition>
        <java:consequence>
            uiview.get("pbmAdembescherming").setInfoMessage("INFO_isobutaan_persluchtmasker");
        </java:consequence>
    </rule>
    <rule name="validator product ammoniak - persoonlijke gelaatsscherm">
        <parameter identifier="object">
            <class>BusinessObjectIF</class>
        </parameter>
        <java:condition>ObjectUtil.hasValue(object,"product","ammoniak")</java:condition>
        <java:consequence>
            uiview.get("pbmGelaatschermRequired").setInfoMessage("INFO_ammoniak_persluchtmasker");
        </java:consequence>
    </rule>
    <rule name="validator product chloor - persoonlijke gelaatsscherm">
        <parameter identifier="object">
            <class>BusinessObjectIF</class>
        </parameter>
        <java:condition>ObjectUtil.hasValue(object,"product","chloor")</java:condition>
        <java:consequence>
            uiview.get("pbmGelaatschermRequired").setInfoMessage("INFO_chloor_persluchtmasker");
        </java:consequence>
    </rule>
    <rule name="validator product ammoniak - persoonlijke beschermende kleding">
        <parameter identifier="object">
            <class>BusinessObjectIF</class>
        </parameter>
        <java:condition>ObjectUtil.hasValue(object,"product","chloor")</java:condition>
        <java:consequence>
            uiview.get("pbmBeschermendeKledingRequired").setInfoMessage("INFO_chloor_pbmBeschermendeKledingRequired");
        </java:consequence>
    </rule>
    <rule name="validator product chloor - persoonlijke hand armbescherming">
        <parameter identifier="object">
            <class>BusinessObjectIF</class>
        </parameter>
        <java:condition>ObjectUtil.hasValue(object,"product","chloor")</java:condition>
        <java:consequence>
            uiview.get("pbmHandArmbeschermingRequired").setInfoMessage("INFO_chloor_pbmHandArmbeschermingRequired");
        </java:consequence>
    </rule>-->

</rule-set>
