<?xml version="1.0"?>

<rule-set name="ibanx_ra_bp1_decorators"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/java java.xsd">

    <java:import>ibanx.persistence.object.PersistableIF</java:import>
    <java:import>ibanx.permit.PermitIF</java:import>
    <java:import>ibanx.tra.RiskAssessmentIF</java:import>
    <java:import>java.lang.String</java:import>
    <java:import>ibanx.util.ValueListUtil</java:import>
    <java:import>ibanx.util.ObjectUtil</java:import>
    <java:import>ibanx.org.UserIF</java:import>

    <application-data identifier="log">org.apache.log4j.Logger</application-data>
    <application-data identifier="applicationSettings">ibanx.configuration.ApplicationSettings</application-data>
    <application-data identifier="errors">java.util.Hashtable</application-data>

    <rule name="decorator Access confined space to enclosed space permit ">
        <parameter identifier="ra"><class>RiskAssessmentIF</class></parameter>
        <java:condition>ObjectUtil.hasValue(ra,"a_wwBetredenBeslotenRuimteRequired","Yes")</java:condition>
        <java:consequence>ObjectUtil.update(ra,"sd_avBeslotenRuimteRequired","Yes");</java:consequence>
    </rule>

    <rule name="decorator Digging to excavation permit ">
        <parameter identifier="ra"><class>RiskAssessmentIF</class></parameter>
        <java:condition>ObjectUtil.hasValue(ra,"a_wwGravenRequired","Yes")</java:condition>
        <java:consequence>ObjectUtil.update(ra,"sd_avGraafVergunningRequired","Yes");</java:consequence>
    </rule>         

</rule-set>