<?xml version="1.0"?>

<rule-set name="presence_permit_decorators"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/java java.xsd">

    <java:import>ibanx.persistence.object.PersistableIF</java:import>
    <java:import>ibanx.permit.PermitIF</java:import>
    <java:import>java.lang.String</java:import>
    <java:import>ibanx.util.ValueListUtil</java:import>
    <java:import>ibanx.util.ObjectUtil</java:import>
    <java:import>ibanx.util.PermitUtil</java:import>
    <java:import>ibanx.util.PermitLinkUtil</java:import>
    <java:import>ibanx.org.UserIF</java:import>

    <application-data identifier="log">org.apache.log4j.Logger</application-data>
    <application-data identifier="applicationSettings">ibanx.configuration.ApplicationSettings</application-data>
    <application-data identifier="errors">java.util.Hashtable</application-data>


</rule-set>
